name: AI Code Review

on:
  # Triggered when a pull request is opened or updated
  pull_request:
    types: [ opened, synchronize ]

  # Triggered when someone comments on a review
  pull_request_review_comment:
    types: [ created ]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: AI Code Review
        uses: utsmannn/corivai@v5
        with:
          reviewer-api-key: ${{ secrets.REVIEWER_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          model-name: 'your-model-name'
          openai-url: 'your-endpoint-url' # optional, default: https://api.openai.com/v1
          max-diff-size: '100000' # optional
          custom-instructions: | # optional
            Your custom review guidelines here
